export function registerAiAssistantRoutes(app, controller, { requireAuth, requirePermission, asyncRoute }) {
  app.get('/api/ai/models', requireAuth, asyncRoute(controller.listModels))
  app.get('/api/ai/agents', requireAuth, asyncRoute(controller.listAgents))
  app.get('/api/admin/ai-agents', requirePermission('platform.ai_agent.read'), asyncRoute(controller.listAdminAgents))
  app.post('/api/admin/ai-agents', requirePermission('platform.ai_agent.create'), asyncRoute(controller.createAgent))
  app.put('/api/admin/ai-agents/:id', requirePermission('platform.ai_agent.write'), asyncRoute(controller.updateAgent))
  app.delete('/api/admin/ai-agents/:id', requirePermission('platform.ai_agent.unlink'), asyncRoute(controller.deleteAgent))
  app.get('/api/ai/knowledge-bases', requireAuth, asyncRoute(controller.listKnowledgeBases))
  app.post('/api/ai/knowledge-bases', requireAuth, asyncRoute(controller.createKnowledgeBase))
  app.post('/api/ai/knowledge-bases/:id/documents', requireAuth, asyncRoute(controller.createKnowledgeDocument))
  app.get('/api/ai/skills', requireAuth, asyncRoute(controller.listSkills))
  app.post('/api/ai/attachments', requireAuth, asyncRoute(controller.uploadAttachment))
  app.get('/api/ai/conversations', requireAuth, asyncRoute(controller.listConversations))
  app.post('/api/ai/conversations', requireAuth, asyncRoute(controller.createConversation))
  app.get('/api/ai/conversations/:id', requireAuth, asyncRoute(controller.getConversation))
  app.delete('/api/ai/conversations/:id', requireAuth, asyncRoute(controller.deleteConversation))
  app.get('/api/ai/conversations/:id/messages', requireAuth, asyncRoute(controller.listMessages))
  app.post('/api/ai/conversations/:id/messages', requireAuth, asyncRoute(controller.sendMessage))
}
