import { useEffect, useState } from 'react'
import { App, Button, Form, Input, InputNumber, Segmented, Spin, Switch, Typography, Upload } from 'antd'
import { DeleteOutlined, SaveOutlined, UploadOutlined } from '@ant-design/icons'
import { api } from '../../api'
import { useAuth } from '../../auth'
import type { SystemSettings } from '../../types'

type AiChatForm = Pick<SystemSettings, 'aiChatWelcome' | 'aiChatFirstPromptCount' | 'aiChatMaxRounds' | 'aiChatFollowupCount' | 'aiChatRobotIcon' | 'aiChatTheme' | 'aiChatEffects'>

export default function AIChatConfig() {
  const { message } = App.useApp(); const { can } = useAuth(); const [loading, setLoading] = useState(true); const [form] = Form.useForm<AiChatForm>()
  useEffect(() => { void (async () => { try { form.setFieldsValue(await api.aiChatSettings()) } catch (error) { message.error((error as Error).message) } finally { setLoading(false) } })() }, [form, message])
  const selectIcon = (file: File) => { if (!file.type.startsWith('image/')) { message.error('请选择图片文件'); return Upload.LIST_IGNORE } if (file.size > 2 * 1024 * 1024) { message.error('机器人图片不能超过 2MB'); return Upload.LIST_IGNORE } const reader = new FileReader(); reader.onload = () => form.setFieldValue('aiChatRobotIcon', String(reader.result)); reader.readAsDataURL(file); return false }
  const save = async (values: AiChatForm) => { try { const next = await api.updateAiChatSettings(values); form.setFieldsValue(next); message.success('AI Chat 配置已保存') } catch (error) { message.error((error as Error).message) } }
  if (loading) return <div className="route-loading"><Spin size="large" /></div>
  return <div><div className="page-title"><div><Typography.Title level={3}>AI Chat 配置</Typography.Title><Typography.Text type="secondary">配置欢迎词、推荐问题、主题和机器人图标</Typography.Text></div><Button type="primary" disabled={!can('platform.settings.write')} icon={<SaveOutlined />} onClick={() => form.submit()}>保存</Button></div><Form form={form} layout="vertical" className="system-settings-form" onFinish={(values) => void save(values)}><Form.Item name="aiChatWelcome" label="欢迎词" rules={[{ required: true, message: '请输入欢迎词' }]}><Input.TextArea rows={3} maxLength={500} showCount /></Form.Item><Form.Item name="aiChatTheme" label="聊天主题"><Segmented block options={[{ label: '明亮', value: 'light' }, { label: '深色', value: 'dark' }, { label: '自然', value: 'nature' }]} /></Form.Item><Form.Item name="aiChatFirstPromptCount" label="首轮对话推荐问题个数" rules={[{ required: true }]}><InputNumber min={0} max={10} precision={0} style={{ width: '100%' }} /></Form.Item><Form.Item name="aiChatMaxRounds" label="多轮对话轮数" rules={[{ required: true }]}><InputNumber min={1} max={100} precision={0} style={{ width: '100%' }} /></Form.Item><Form.Item name="aiChatFollowupCount" label="对话后问题推荐个数" rules={[{ required: true }]}><InputNumber min={0} max={10} precision={0} style={{ width: '100%' }} /></Form.Item><Form.Item name="aiChatEffects" label="聊天动态效果" valuePropName="checked" extra="关闭后保留静态界面，适合对动效敏感或低性能设备"><Switch checkedChildren="开启" unCheckedChildren="关闭" /></Form.Item><Form.Item label="CHAT 机器人图标" extra="支持 PNG、JPG、WebP、GIF、APNG，最大 2MB；GIF/APNG 保留动效"><Form.Item noStyle shouldUpdate={(before, after) => before.aiChatRobotIcon !== after.aiChatRobotIcon}>{() => { const value = form.getFieldValue('aiChatRobotIcon') as string | undefined; return <Upload accept="image/*" beforeUpload={selectIcon} showUploadList={false}>{value ? <div className="image-upload-card"><img src={value} alt="CHAT 机器人图标" /><button type="button" className="image-action image-delete" title="删除图片" onClick={(event) => { event.preventDefault(); event.stopPropagation(); form.setFieldValue('aiChatRobotIcon', null) }}><DeleteOutlined /></button></div> : <button type="button" className="image-upload-card image-upload-empty"><UploadOutlined /><span>点击上传</span></button>}</Upload> }}</Form.Item><Form.Item name="aiChatRobotIcon" hidden><Input /></Form.Item></Form.Item></Form></div>
}
