import { Layout, Menu, Button, Typography } from 'antd'
import { AppstoreOutlined, HomeOutlined, LogoutOutlined, SettingOutlined, UserOutlined } from '@ant-design/icons'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth'
import { useSystemSettings } from '../../system-settings'

export default function ConfigLayout({ onLogout }: { onLogout: () => void }) {
  const navigate = useNavigate(); const location = useLocation(); const { user } = useAuth()
  const { settings, defaultLogo } = useSystemSettings()
  const selectedKey = location.pathname.includes('/basic-config') ? 'basic-config' : location.pathname.includes('/system-security') ? 'system-security' : location.pathname.includes('/sso/inbound') ? 'sso-inbound' : location.pathname.includes('/sso/outbound') ? 'sso-outbound' : location.pathname.includes('users') ? 'users' : location.pathname.includes('dashboard') ? 'dashboard' : 'workbench'
  return <Layout className="config-layout"><Layout.Sider width={240} theme="light"><div className="sider-brand"><img className="brand-mark small" src={settings.systemLogo || defaultLogo} alt={settings.systemTitle} /><strong>{settings.systemTitle}</strong></div><Menu mode="inline" selectedKeys={[selectedKey]} items={[{ key: 'workbench', icon: <HomeOutlined />, label: '工作台', onClick: () => navigate('/') }, { key: 'dashboard', icon: <AppstoreOutlined />, label: '工作台配置', onClick: () => navigate('/config/dashboard') }, { key: 'users', icon: <UserOutlined />, label: '用户管理', onClick: () => navigate('/config/users') }, { key: 'system-config', icon: <SettingOutlined />, label: '系统配置', children: [{ key: 'basic-config', label: '基础配置', onClick: () => navigate('/config/basic-config') }, { key: 'system-security', label: '系统安全', onClick: () => navigate('/config/system-security') }, { key: 'sso-config', label: '单点登录', children: [{ key: 'sso-inbound', label: '外部访入', onClick: () => navigate('/config/sso/inbound') }, { key: 'sso-outbound', label: '内部访出', onClick: () => navigate('/config/sso/outbound') }] }] }]} /></Layout.Sider><Layout><Layout.Header className="config-header"><Button type="text" onClick={() => navigate('/config/dashboard')}>控制台</Button><Typography.Text>{user!.name}</Typography.Text><Button type="text" icon={<LogoutOutlined />} onClick={onLogout}>退出</Button></Layout.Header><Layout.Content className="config-content"><Outlet /></Layout.Content>{settings.footerRecord && <Layout.Footer className="config-footer">{settings.footerRecord}</Layout.Footer>}</Layout></Layout>
}
