import { useEffect, useMemo, useState } from 'react'
import { App, Button, Drawer, Form, Image, Input, InputNumber, Space, Switch, Table, Upload, Select, Typography } from 'antd'
import { DeleteOutlined, DownloadOutlined, PlusOutlined, UploadOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { DashboardApp, User } from '../../types'
import { api } from '../../api'

export default function DashboardConfig() {
  const { message } = App.useApp(); const navigate = useNavigate(); const [apps, setApps] = useState<DashboardApp[]>([]); const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<DashboardApp | null>(null); const [drawer, setDrawer] = useState(false); const [form] = Form.useForm<DashboardApp>(); const [checked, setChecked] = useState<number[]>([]); const [dragId, setDragId] = useState<number | null>(null)
  const load = async () => { setLoading(true); try { const [appRows, userRows] = await Promise.all([api.adminApps(), api.users()]); setApps(appRows); setUsers(userRows) } catch (error) { message.error((error as Error).message) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const openCreate = () => { setSelected(null); form.resetFields(); form.setFieldsValue({ enabled: true, priority: apps.length + 1, userIds: [] }); setDrawer(true) }
  const openEdit = (row: DashboardApp) => { setSelected(row); form.setFieldsValue(row); setDrawer(true) }
  const save = async (values: DashboardApp) => { try { if (selected) await api.updateApp(selected.id, { ...selected, ...values }); else await api.createApp(values); setDrawer(false); await load(); message.success('保存成功') } catch (error) { message.error((error as Error).message) } }
  const remove = async (id: number) => { try { await api.deleteApp(id); setChecked((ids) => ids.filter((item) => item !== id)); await load(); message.success('已删除') } catch (error) { message.error((error as Error).message) } }
  const batchDelete = async () => { try { await api.deleteApps(checked); setChecked([]); await load(); message.success('已删除选中记录') } catch (error) { message.error((error as Error).message) } }
  const toggleVisible = async (id: number, enabled: boolean) => { const previous = apps; setApps((rows) => rows.map((row) => row.id === id ? { ...row, enabled } : row)); try { await api.toggleApp(id, enabled); message.success(enabled ? '已显示在工作台' : '已从工作台隐藏') } catch (error) { setApps(previous); message.error((error as Error).message) } }
  const reorder = async (targetId: number) => { if (dragId === null || dragId === targetId) return; const sorted = [...apps].sort((a,b) => a.priority-b.priority); const from = sorted.findIndex((a) => a.id === dragId); const to = sorted.findIndex((a) => a.id === targetId); if (from < 0 || to < 0) return; const [item] = sorted.splice(from, 1); sorted.splice(to, 0, item); const next = sorted.map((a, i) => ({ ...a, priority: i + 1 })); setApps(next); setDragId(null); try { await api.reorderApps(next.map((row) => row.id)); message.success('排序已更新') } catch (error) { await load(); message.error((error as Error).message) } }
  const uploadImage = (file: File) => { if (!file.type.startsWith('image/')) { message.error('请选择图片文件'); return Upload.LIST_IGNORE } if (file.size > 10 * 1024 * 1024) { message.error('图片不能超过 10MB'); return Upload.LIST_IGNORE } const reader = new FileReader(); reader.onload = () => { form.setFieldsValue({ img: String(reader.result), imgThumbnail: String(reader.result), imgFileName: file.name }); message.success('图片已选择，保存后上传') }; reader.readAsDataURL(file); return false }
  const downloadOriginal = () => { const source = form.getFieldValue('img'); if (!source) return; const anchor = document.createElement('a'); anchor.href = source; anchor.download = form.getFieldValue('imgFileName') || '应用图标'; document.body.appendChild(anchor); anchor.click(); anchor.remove() }
  const clearImage = () => form.setFieldsValue({ img: undefined, imgThumbnail: undefined, imgFileName: undefined })
  const columns = useMemo(() => [{ title: '序号', width: 70, render: (_: unknown, __: DashboardApp, index: number) => index + 1 }, { title: '图标', width: 75, render: (_: unknown, row: DashboardApp) => row.imgThumbnail || row.img ? <Image width={36} height={36} src={row.imgThumbnail || row.img} /> : <span className="table-fallback">{row.name.slice(0,1)}</span> }, { title: '编码', dataIndex: 'code' }, { title: '名称', dataIndex: 'name' }, { title: '优先级', dataIndex: 'priority', width: 90 }, { title: '显示', dataIndex: 'enabled', width: 80, render: (value: boolean, row: DashboardApp) => <Switch size="small" checked={value} onChange={(value) => void toggleVisible(row.id, value)} /> }, { title: '操作', width: 150, render: (_: unknown, row: DashboardApp) => <Space><Button type="link" onClick={() => openEdit(row)}>编辑</Button><Button type="link" danger onClick={() => void remove(row.id)}>删除</Button></Space> }], [apps])
  return <div><div className="page-title"><div><Typography.Title level={3}>工作台配置</Typography.Title><Typography.Text type="secondary">管理工作台应用入口与可见范围</Typography.Text></div><Space><Button onClick={() => navigate('/')}>工作台</Button><Button danger icon={<DeleteOutlined />} disabled={!checked.length} onClick={() => void batchDelete()}>删除选中</Button><Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>创建</Button></Space></div><Table loading={loading} rowKey="id" columns={columns} dataSource={[...apps].sort((a,b) => a.priority-b.priority)} rowSelection={{ selectedRowKeys: checked, onChange: (keys) => setChecked(keys as number[]) }} pagination={{ pageSize: 50 }} onRow={(record) => ({ draggable: true, onDragStart: () => setDragId(record.id), onDragOver: (event) => event.preventDefault(), onDrop: () => void reorder(record.id), onClick: (event) => { if ((event.target as HTMLElement).closest('button,.ant-checkbox-wrapper,.ant-switch')) return; openEdit(record) } })} />
    <Drawer title={selected ? '编辑应用' : '创建应用'} width={480} open={drawer} onClose={() => setDrawer(false)} destroyOnClose extra={<Button type="primary" onClick={() => form.submit()}>保存</Button>}><Form form={form} layout="vertical" onFinish={(values) => void save(values)}><Form.Item name="name" label="名称" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="code" label="编码" rules={[{ required: true }]}><Input disabled={!!selected} /></Form.Item><Form.Item name="priority" label="优先级" rules={[{ required: true }]}><InputNumber min={1} style={{ width: '100%' }} /></Form.Item><Form.Item name="url" label="访问链接" rules={[{ required: true, type: 'url' }]}><Input placeholder="https://" /></Form.Item><Form.Item name="userIds" label="指定用户" extra="不选择用户时，所有用户均可访问"><Select mode="multiple" allowClear options={users.map((u) => ({ label: `${u.name} (${u.code})`, value: u.id }))} /></Form.Item><Form.Item label="图标"><Form.Item noStyle shouldUpdate={(before, after) => before.img !== after.img || before.imgThumbnail !== after.imgThumbnail}>{() => { const original = form.getFieldValue('img'); const thumbnail = form.getFieldValue('imgThumbnail'); return original ? <div className="image-upload-card"><img src={thumbnail || original} alt="应用图标" /><div className="image-action image-download" title="下载原图" onClick={downloadOriginal}><DownloadOutlined /></div><div className="image-action image-delete" title="删除图片" onClick={clearImage}><DeleteOutlined /></div></div> : <Upload accept="image/*" beforeUpload={uploadImage} showUploadList={false}><button type="button" className="image-upload-card image-upload-empty"><UploadOutlined /><span>点击上传</span></button></Upload> }}</Form.Item><Form.Item name="img" hidden><Input /></Form.Item><Form.Item name="imgThumbnail" hidden><Input /></Form.Item><Form.Item name="imgFileName" hidden><Input /></Form.Item></Form.Item><Form.Item name="enabled" label="显示" valuePropName="checked" extra="开启后显示在工作台"><Switch /></Form.Item></Form></Drawer></div>
}
